package vista;

/**
 *
 * @author monse
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEstudiante = new javax.swing.JButton();
        btnBeneficios = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnAsignarBene = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuModulo = new javax.swing.JMenu();
        mntEstudiante = new javax.swing.JMenuItem();
        mntBeneficios = new javax.swing.JMenuItem();
        mntCarreras = new javax.swing.JMenuItem();
        mntAsignarBene = new javax.swing.JMenuItem();
        mntGestionPago = new javax.swing.JMenuItem();
        mnuAcerca = new javax.swing.JMenu();
        mntAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEstudiante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconEstudiante.png"))); // NOI18N
        btnEstudiante.setText("Estudiante");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        btnBeneficios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBeneficios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBeneficio.png"))); // NOI18N
        btnBeneficios.setText("Beneficios");
        btnBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeneficiosActionPerformed(evt);
            }
        });

        btnCarreras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCarrera.png"))); // NOI18N
        btnCarreras.setText("Carreras");
        btnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrerasActionPerformed(evt);
            }
        });

        btnAsignarBene.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAsignarBene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAsignarBeneficio.png"))); // NOI18N
        btnAsignarBene.setText("Asignar Beneficios");
        btnAsignarBene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBeneActionPerformed(evt);
            }
        });

        btnPagos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPago.png"))); // NOI18N
        btnPagos.setText("Gestión de Pagos");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnAsignarBene, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btnBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarBene, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        mnuModulo.setText("Módulos");

        mntEstudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mntEstudiante.setText("Estudiante");
        mnuModulo.add(mntEstudiante);

        mntBeneficios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mntBeneficios.setText("Beneficios");
        mnuModulo.add(mntBeneficios);

        mntCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mntCarreras.setText("Carreras");
        mntCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntCarrerasActionPerformed(evt);
            }
        });
        mnuModulo.add(mntCarreras);

        mntAsignarBene.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mntAsignarBene.setText("Asignar Beneficios");
        mnuModulo.add(mntAsignarBene);

        mntGestionPago.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mntGestionPago.setText("Gestión de Pagos");
        mnuModulo.add(mntGestionPago);

        jMenuBar1.add(mnuModulo);

        mnuAcerca.setText("Acerca de");

        mntAbout.setText("About");
        mntAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAboutActionPerformed(evt);
            }
        });
        mnuAcerca.add(mntAbout);

        jMenuBar1.add(mnuAcerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeneficiosActionPerformed
        // TODO add your handling code here:
        DlgBeneficios dialog = new DlgBeneficios((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBeneficiosActionPerformed

    private void btnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrerasActionPerformed
        // TODO add your handling code here:
        DlgCarrera dialog = new DlgCarrera((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCarrerasActionPerformed

    private void mntCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntCarrerasActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        // TODO add your handling code here:
        DlgEstudiante dialog = new DlgEstudiante((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnAsignarBeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBeneActionPerformed
        // TODO add your handling code here:
        DlgAsignarBeneficios dialog = new DlgAsignarBeneficios((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAsignarBeneActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        DlgPagosMensuales dialog = new DlgPagosMensuales((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void mntAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAboutActionPerformed
        DlgAbout aboutDialog = new DlgAbout(this, true);
        aboutDialog.setLocationRelativeTo(this);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_mntAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBene;
    private javax.swing.JButton btnBeneficios;
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnPagos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mntAbout;
    private javax.swing.JMenuItem mntAsignarBene;
    private javax.swing.JMenuItem mntBeneficios;
    private javax.swing.JMenuItem mntCarreras;
    private javax.swing.JMenuItem mntEstudiante;
    private javax.swing.JMenuItem mntGestionPago;
    private javax.swing.JMenu mnuAcerca;
    private javax.swing.JMenu mnuModulo;
    // End of variables declaration//GEN-END:variables
}
